title: Blog de análises
description: descrição do blog

url: http://guilhermeagsouza.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Início
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: guilhermeagsouza
  twitter: guilhermeohaxa
  facebook: araujo.blues
  email: guilherme.cdados@gmail.com
  linkedin: guilhermeagsouza

google_analytics: "GOOGLES ANALYTICS"
